/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsGroupIdRouteRouteImport } from './routes/groups/$groupId/route'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdBillsIndexRouteImport } from './routes/groups/$groupId/bills/index'
import { Route as GroupsGroupIdBillsNewRouteImport } from './routes/groups/$groupId/bills/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRouteRoute = GroupsGroupIdRouteRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any)
const GroupsGroupIdBillsIndexRoute = GroupsGroupIdBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any)
const GroupsGroupIdBillsNewRoute = GroupsGroupIdBillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/bills/new': typeof GroupsGroupIdBillsNewRoute
  '/groups/$groupId/bills/': typeof GroupsGroupIdBillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/bills/new': typeof GroupsGroupIdBillsNewRoute
  '/groups/$groupId/bills': typeof GroupsGroupIdBillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/bills/new': typeof GroupsGroupIdBillsNewRoute
  '/groups/$groupId/bills/': typeof GroupsGroupIdBillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/groups/$groupId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/bills/new'
    | '/groups/$groupId/bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/bills/new'
    | '/groups/$groupId/bills'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/groups/$groupId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/bills/new'
    | '/groups/$groupId/bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  GroupsGroupIdRouteRoute: typeof GroupsGroupIdRouteRouteWithChildren
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/bills/': {
      id: '/groups/$groupId/bills/'
      path: '/bills'
      fullPath: '/groups/$groupId/bills/'
      preLoaderRoute: typeof GroupsGroupIdBillsIndexRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/bills/new': {
      id: '/groups/$groupId/bills/new'
      path: '/bills/new'
      fullPath: '/groups/$groupId/bills/new'
      preLoaderRoute: typeof GroupsGroupIdBillsNewRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
  }
}

interface GroupsGroupIdRouteRouteChildren {
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdBillsNewRoute: typeof GroupsGroupIdBillsNewRoute
  GroupsGroupIdBillsIndexRoute: typeof GroupsGroupIdBillsIndexRoute
}

const GroupsGroupIdRouteRouteChildren: GroupsGroupIdRouteRouteChildren = {
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdBillsNewRoute: GroupsGroupIdBillsNewRoute,
  GroupsGroupIdBillsIndexRoute: GroupsGroupIdBillsIndexRoute,
}

const GroupsGroupIdRouteRouteWithChildren =
  GroupsGroupIdRouteRoute._addFileChildren(GroupsGroupIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  GroupsGroupIdRouteRoute: GroupsGroupIdRouteRouteWithChildren,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
